export const SPORTS = [
  "Athletics",
  "Badminton",
  "Baseball",
  "Basketball",
  "Boxing",
  "Cricket",
  "CrossFit",
  "Cycling",
  "Field Hockey",
  "American Football",
  "Golf",
  "Gymnastics",
  "Rugby",
  "Soccer",
  "Swimming",
  "Table Tennis",
  "Tennis",
  "Volleyball",
  "Weightlifting",
  "Wrestling",
] as const;

export const POSITIONS_BY_SPORT: Record<string, string[]> = {
  Athletics: ["Sprinter", "Middle-distance runner", "Long-distance runner", "Hurdler", "Jumper", "Thrower", "Combined-events athlete"],
  Badminton: ["Singles player", "Doubles player"],
  Baseball: ["Pitcher", "Catcher", "Infielder", "Outfielder", "Designated hitter"],
  Basketball: ["Point Guard", "Shooting Guard", "Small Forward", "Power Forward", "Center"],
  Boxing: ["Boxer"],
  Cricket: ["Batter", "Bowler", "All-rounder", "Wicketkeeper"],
  CrossFit: ["CrossFit athlete"],
  Cycling: ["Road cyclist", "Track cyclist", "Mountain biker", "BMX rider"],
  "Field Hockey": ["Goalkeeper", "Defender", "Midfielder", "Forward"],
  "American Football": ["Quarterback", "Running back", "Wide receiver", "Tight end", "Offensive line", "Defensive line", "Linebacker", "Defensive back", "Kicker / punter"],
  Golf: ["Golfer"],
  Gymnastics: ["Artistic gymnast", "Rhythmic gymnast", "Trampoline gymnast"],
  Rugby: ["Prop", "Hooker", "Lock", "Flanker", "Number eight", "Scrum-half", "Fly-half", "Centre", "Wing", "Fullback"],
  Soccer: ["Goalkeeper", "Defender", "Midfielder", "Winger", "Forward"],
  Swimming: ["Freestyle swimmer", "Backstroke swimmer", "Breaststroke swimmer", "Butterfly swimmer", "Medley swimmer", "Open-water swimmer"],
  "Table Tennis": ["Singles player", "Doubles player"],
  Tennis: ["Singles player", "Doubles player"],
  Volleyball: ["Setter", "Outside hitter", "Opposite hitter", "Middle blocker", "Libero"],
  Weightlifting: ["Weightlifter"],
  Wrestling: ["Freestyle wrestler", "Greco-Roman wrestler"],
};

export const EVENTS_BY_SPORT: Record<string, string[]> = {
  Athletics: ["100m Sprint", "200m Sprint", "400m Sprint", "800m", "1500m", "5km", "10km Road Race", "Marathon", "Hurdles", "Long jump", "High jump", "Throws", "Combined events"],
  Badminton: ["Singles", "Doubles", "Mixed doubles"],
  Baseball: ["Match"],
  Basketball: ["Match", "Training session"],
  Boxing: ["Bout", "Sparring session"],
  Cricket: ["Test match", "One Day match", "T20 match", "Training session"],
  CrossFit: ["Competition", "Benchmark session", "Training session"],
  Cycling: ["Road race", "Time trial", "Track event", "Mountain bike race", "BMX race"],
  "Field Hockey": ["Match", "Training session"],
  "American Football": ["Match", "Training session"],
  Golf: ["Tournament round", "Training round"],
  Gymnastics: ["All-around", "Apparatus event", "Team event"],
  Rugby: ["Match", "Training session"],
  Soccer: ["Match", "Training session"],
  Swimming: ["50m Freestyle", "100m Freestyle", "200m Freestyle", "Backstroke", "Breaststroke", "Butterfly", "Individual medley", "Open water"],
  "Table Tennis": ["Singles", "Doubles", "Mixed doubles"],
  Tennis: ["Singles", "Doubles", "Mixed doubles"],
  Volleyball: ["Match", "Training session"],
  Weightlifting: ["Snatch", "Clean and jerk", "Total"],
  Wrestling: ["Freestyle bout", "Greco-Roman bout"],
};
